import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Blogs() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Jonatan Ochoa</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      

      <main className={styles.main}>
        <h2 className={styles.title}>My blog</h2>
        <button className={styles.card}>
          Sign In
        </button>
      </main>
    </div>
  );
}
