import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { Button } from '../components/Navbar.elements';
import Blogs from './Blogs';
import Card from './Card';
import About from './About';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Jonatan Ochoa</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Jona Developer
        </h1>
        <Button>Sing In</Button>
      </main>
      <About />
      <Blogs />
      <Card/>
    </div>
  ) 
}
